
name: Popular frameworks

on:
    push:
        branches:
            - master
    pull_request: ~

jobs:
    symfony:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: true
            matrix:
                os: [ubuntu-latest]
                version: ['@dev'] # Test current LTS, current release, and future release
                php: ['8.1']
                composer-version: [v2]
        env:
            allow_failure: ${{ matrix.version == '@dev' }}
        name: "Symfony skeleton:${{ matrix.version }} - PHP${{ matrix.php }} - Composer ${{ matrix.composer-version }}"

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  path: phpinsights
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, mbstring, zip
                  coverage: none
                  tools: composer:${{ matrix.composer-version }}

            - name: Install Symfony Skeleton
              run: composer create-project --no-progress --ansi symfony/skeleton:${{matrix.version}} project
              continue-on-error: ${{ env.allow_failure == 'true' }}
            - name: Improve composer
              working-directory: ./project
              run: |
                  composer config name phpinsights/symfony-tester
                  composer config description "Symfony test"
              continue-on-error: ${{ env.allow_failure == 'true' }}
            - name: Linking library
              working-directory: ./project
              run: |
                composer config repositories.phpinsights '{"type":"path", "url": "../phpinsights/", "options":{"symlink": false}}'
              continue-on-error: ${{ env.allow_failure == 'true' }}
            - name: Composer config
              working-directory: ./project
              run: |
                  composer config prefer-stable true
                  composer config minimum-stability dev
              continue-on-error: ${{ env.allow_failure == 'true' }}
            - name: Require psr/simple-cache
              working-directory: ./project
              run: composer require "psr/simple-cache:${{ matrix.psr-simple-cache-version }}"
              continue-on-error: ${{ env.allow_failure == 'true' }}
            - name: Allow plugin
              working-directory: ./project
              run: composer config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
              continue-on-error: ${{ env.allow_failure == 'true' }}
            - name: Install PHPInsights
              working-directory: ./project
              run: composer require --dev "nunomaduro/phpinsights:*" -n --ansi --with-all-dependencies
              continue-on-error: true
            - name: Launch PHPInsights
              working-directory: ./project
              run: php vendor/bin/phpinsights -n --disable-security-check --ansi
              continue-on-error: ${{ env.allow_failure == 'true' }}
            - name: Launch PHPInsights Fixer
              working-directory: ./project
              run: php vendor/bin/phpinsights fix -n --ansi
              continue-on-error: ${{ env.allow_failure == 'true' 
