name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 # or alternative dependency manageme

    - uses: stefanzweifel/phpinsights-action@v1.1.1

    # ... then your own project steps ...
